name: Auto Fetch Clash Nodes

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  fetch-nodes:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Prepare output directories
      run: mkdir -p snippets

    - name: Run fetch.py
      run: python fetch.py

    - name: Commit and Push if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add list.yml list.txt
        git diff --cached --quiet || git commit -m "auto: update nodes by GitHub Actions"
        git push
